name: Latest blog post & Update Profile README

on:
  schedule:
    - cron: "30 6 */1 * *"  # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
            
      - name: Update README with latest articles
      - uses: gautamkrishnar/blog-post-workflow@master 
      # uses: Prachi-Jamdade/Prachi-Jamdade@v1.1.0
        with:
          feed_urls: 'https://news.ycombinator.com/rss, https://feeds.feedburner.com/ruanyifeng'
          article_limit: 5
          max_post_count: "5"
      # feed_list: "https://medium.com/feed/@molly1024"
          article_type: 'recent'
          github_token: ${{ secrets.TOKEN_GITHUB }}
